services:
  rabbitmq:
    build:
      dockerfile: ./Dockerfile
    ports: ["15672:15672", "5672:5672", "5671:5671", "15675:15675", "1883:1883"]
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: bitnami
    volumes:
      - ./rabbitmq_conf/server/server_AMQPRS_TEST_key.pem:/etc/ssl/server_AMQPRS_TEST_key.pem
      - ./rabbitmq_conf/server/server_AMQPRS_TEST_certificate.pem:/etc/ssl/server_AMQPRS_TEST_certificate.pem
      - ./rabbitmq_conf/server/ca_certificate.pem:/etc/ssl/ca_certificate.pem
      - ./rabbitmq_conf/custom.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - rmq_data:/var/lib/rabbitmq/

volumes:
  rmq_data:
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: "size=35840m"